# Generated by Django 4.0.4 on 2022-09-07 04:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='followrelationship',
            constraint=models.UniqueConstraint(fields=('follower', 'followee'), name='follow_unique'),
        ),
    ]
