# Generated by Django 4.0.4 on 2022-09-12 05:04

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_followrelationship_follow_unique'),
    ]

    operations = [
        migrations.CreateModel(
            name='LikeRelationship',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tweet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.tweet')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='liked_by', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddConstraint(
            model_name='likerelationship',
            constraint=models.UniqueConstraint(fields=('tweet', 'user'), name='like_unique'),
        ),
    ]
