# Generated by Django 2.2.24 on 2022-01-30 01:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_auto_20220127_1105'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='age',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
    ]
